name: _
publish_to: none

environment:
  sdk: ^3.8.1
workspace:
  - cli
  - command_runner
  - wikipedia

name: cli
description: A sample command-line application.
version: 1.0.0
resolution: workspace

name: command_runner
description: A starting point for Dart libraries or applications.
version: 1.0.0
resolution: workspace

name: wikipedia
description: A sample command-line application.
version: 1.0.0
resolution: workspace



